export interface CountryOption {
  name: string;
  code: string;
  currency: string;
  currencyCode: string;
  phoneCode: string;
  timezone: string;
}

export const getCountryFlag = (code: string) => {
  if (!code) return "🌐";
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(char.charCodeAt(0) + 127397));
};

export const COUNTRIES: CountryOption[] = [
  { name: "Afghanistan", code: "AF", currency: "AFN (؋) - Afghan Afghani", currencyCode: "AFN", phoneCode: "+93", timezone: "Asia/Kabul" },
  { name: "Albania", code: "AL", currency: "ALL (L) - Albanian Lek", currencyCode: "ALL", phoneCode: "+355", timezone: "Europe/Tirane" },
  { name: "Algeria", code: "DZ", currency: "DZD (د.ج) - Algerian Dinar", currencyCode: "DZD", phoneCode: "+213", timezone: "Africa/Algiers" },
  { name: "Andorra", code: "AD", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+376", timezone: "Europe/Andorra" },
  { name: "Angola", code: "AO", currency: "AOA (Kz) - Angolan Kwanza", currencyCode: "AOA", phoneCode: "+244", timezone: "Africa/Luanda" },
  { name: "Argentina", code: "AR", currency: "ARS ($) - Argentine Peso", currencyCode: "ARS", phoneCode: "+54", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Armenia", code: "AM", currency: "AMD (֏) - Armenian Dram", currencyCode: "AMD", phoneCode: "+374", timezone: "Asia/Yerevan" },
  { name: "Australia", code: "AU", currency: "AUD ($) - Australian Dollar", currencyCode: "AUD", phoneCode: "+61", timezone: "Australia/Sydney" },
  { name: "Austria", code: "AT", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+43", timezone: "Europe/Vienna" },
  { name: "Azerbaijan", code: "AZ", currency: "AZN (₼) - Azerbaijani Manat", currencyCode: "AZN", phoneCode: "+994", timezone: "Asia/Baku" },
  { name: "Bahamas", code: "BS", currency: "BSD ($) - Bahamian Dollar", currencyCode: "BSD", phoneCode: "+1-242", timezone: "America/Nassau" },
  { name: "Bahrain", code: "BH", currency: "BHD (.د.ب) - Bahraini Dinar", currencyCode: "BHD", phoneCode: "+973", timezone: "Asia/Bahrain" },
  { name: "Bangladesh", code: "BD", currency: "BDT (৳) - Bangladeshi Taka", currencyCode: "BDT", phoneCode: "+880", timezone: "Asia/Dhaka" },
  { name: "Barbados", code: "BB", currency: "BBD ($) - Barbadian Dollar", currencyCode: "BBD", phoneCode: "+1-246", timezone: "America/Barbados" },
  { name: "Belarus", code: "BY", currency: "BYN (Br) - Belarusian Ruble", currencyCode: "BYN", phoneCode: "+375", timezone: "Europe/Minsk" },
  { name: "Belgium", code: "BE", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+32", timezone: "Europe/Brussels" },
  { name: "Belize", code: "BZ", currency: "BZD ($) - Belize Dollar", currencyCode: "BZD", phoneCode: "+501", timezone: "America/Belize" },
  { name: "Benin", code: "BJ", currency: "XOF (CFA) - West African CFA Franc", currencyCode: "XOF", phoneCode: "+229", timezone: "Africa/Porto-Novo" },
  { name: "Bhutan", code: "BT", currency: "BTN (Nu.) - Bhutanese Ngultrum", currencyCode: "BTN", phoneCode: "+975", timezone: "Asia/Thimphu" },
  { name: "Bolivia", code: "BO", currency: "BOB (Bs.) - Bolivian Boliviano", currencyCode: "BOB", phoneCode: "+591", timezone: "America/La_Paz" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM (KM) - Bosnia-Herzegovina Convertible Mark", currencyCode: "BAM", phoneCode: "+387", timezone: "Europe/Sarajevo" },
  { name: "Botswana", code: "BW", currency: "BWP (P) - Botswana Pula", currencyCode: "BWP", phoneCode: "+267", timezone: "Africa/Gaborone" },
  { name: "Brazil", code: "BR", currency: "BRL (R$) - Brazilian Real", currencyCode: "BRL", phoneCode: "+55", timezone: "America/Sao_Paulo" },
  { name: "Brunei", code: "BN", currency: "BND ($) - Brunei Dollar", currencyCode: "BND", phoneCode: "+673", timezone: "Asia/Brunei" },
  { name: "Bulgaria", code: "BG", currency: "BGN (лв) - Bulgarian Lev", currencyCode: "BGN", phoneCode: "+359", timezone: "Europe/Sofia" },
  { name: "Burkina Faso", code: "BF", currency: "XOF (CFA) - West African CFA Franc", currencyCode: "XOF", phoneCode: "+226", timezone: "Africa/Ouagadougou" },
  { name: "Burundi", code: "BI", currency: "BIF (FBu) - Burundian Franc", currencyCode: "BIF", phoneCode: "+257", timezone: "Africa/Bujumbura" },
  { name: "Cambodia", code: "KH", currency: "KHR (៛) - Cambodian Riel", currencyCode: "KHR", phoneCode: "+855", timezone: "Asia/Phnom_Penh" },
  { name: "Cameroon", code: "CM", currency: "XAF (FCFA) - Central African CFA Franc", currencyCode: "XAF", phoneCode: "+237", timezone: "Africa/Douala" },
  { name: "Canada", code: "CA", currency: "CAD ($) - Canadian Dollar", currencyCode: "CAD", phoneCode: "+1", timezone: "America/Toronto" },
  { name: "Chile", code: "CL", currency: "CLP ($) - Chilean Peso", currencyCode: "CLP", phoneCode: "+56", timezone: "America/Santiago" },
  { name: "China", code: "CN", currency: "CNY (¥) - Chinese Yuan", currencyCode: "CNY", phoneCode: "+86", timezone: "Asia/Shanghai" },
  { name: "Colombia", code: "CO", currency: "COP ($) - Colombian Peso", currencyCode: "COP", phoneCode: "+57", timezone: "America/Bogota" },
  { name: "Costa Rica", code: "CR", currency: "CRC (₡) - Costa Rican Colón", currencyCode: "CRC", phoneCode: "+506", timezone: "America/Costa_Rica" },
  { name: "Croatia", code: "HR", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+385", timezone: "Europe/Zagreb" },
  { name: "Cuba", code: "CU", currency: "CUP ($) - Cuban Peso", currencyCode: "CUP", phoneCode: "+53", timezone: "America/Havana" },
  { name: "Cyprus", code: "CY", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+357", timezone: "Asia/Nicosia" },
  { name: "Czech Republic", code: "CZ", currency: "CZK (Kč) - Czech Koruna", currencyCode: "CZK", phoneCode: "+420", timezone: "Europe/Prague" },
  { name: "Denmark", code: "DK", currency: "DKK (kr) - Danish Krone", currencyCode: "DKK", phoneCode: "+45", timezone: "Europe/Copenhagen" },
  { name: "Dominican Republic", code: "DO", currency: "DOP (RD$) - Dominican Peso", currencyCode: "DOP", phoneCode: "+1-809", timezone: "America/Santo_Domingo" },
  { name: "Ecuador", code: "EC", currency: "USD ($) - US Dollar", currencyCode: "USD", phoneCode: "+593", timezone: "America/Guayaquil" },
  { name: "Egypt", code: "EG", currency: "EGP (E£) - Egyptian Pound", currencyCode: "EGP", phoneCode: "+20", timezone: "Africa/Cairo" },
  { name: "El Salvador", code: "SV", currency: "USD ($) - US Dollar", currencyCode: "USD", phoneCode: "+503", timezone: "America/El_Salvador" },
  { name: "Estonia", code: "EE", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+372", timezone: "Europe/Tallinn" },
  { name: "Ethiopia", code: "ET", currency: "ETB (Br) - Ethiopian Birr", currencyCode: "ETB", phoneCode: "+251", timezone: "Africa/Addis_Ababa" },
  { name: "Fiji", code: "FJ", currency: "FJD ($) - Fijian Dollar", currencyCode: "FJD", phoneCode: "+679", timezone: "Pacific/Fiji" },
  { name: "Finland", code: "FI", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+358", timezone: "Europe/Helsinki" },
  { name: "France", code: "FR", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+33", timezone: "Europe/Paris" },
  { name: "Georgia", code: "GE", currency: "GEL (₾) - Georgian Lari", currencyCode: "GEL", phoneCode: "+995", timezone: "Asia/Tbilisi" },
  { name: "Germany", code: "DE", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+49", timezone: "Europe/Berlin" },
  { name: "Ghana", code: "GH", currency: "GHS (GH₵) - Ghanaian Cedi", currencyCode: "GHS", phoneCode: "+233", timezone: "Africa/Accra" },
  { name: "Greece", code: "GR", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+30", timezone: "Europe/Athens" },
  { name: "Guatemala", code: "GT", currency: "GTQ (Q) - Guatemalan Quetzal", currencyCode: "GTQ", phoneCode: "+502", timezone: "America/Guatemala" },
  { name: "Honduras", code: "HN", currency: "HNL (L) - Honduran Lempira", currencyCode: "HNL", phoneCode: "+504", timezone: "America/Tegucigalpa" },
  { name: "Hong Kong", code: "HK", currency: "HKD ($) - Hong Kong Dollar", currencyCode: "HKD", phoneCode: "+852", timezone: "Asia/Hong_Kong" },
  { name: "Hungary", code: "HU", currency: "HUF (Ft) - Hungarian Forint", currencyCode: "HUF", phoneCode: "+36", timezone: "Europe/Budapest" },
  { name: "Iceland", code: "IS", currency: "ISK (kr) - Icelandic Króna", currencyCode: "ISK", phoneCode: "+354", timezone: "Atlantic/Reykjavik" },
  { name: "India", code: "IN", currency: "INR (₹) - Indian Rupee", currencyCode: "INR", phoneCode: "+91", timezone: "Asia/Kolkata" },
  { name: "Indonesia", code: "ID", currency: "IDR (Rp) - Indonesian Rupiah", currencyCode: "IDR", phoneCode: "+62", timezone: "Asia/Jakarta" },
  { name: "Iran", code: "IR", currency: "IRR (﷼) - Iranian Rial", currencyCode: "IRR", phoneCode: "+98", timezone: "Asia/Tehran" },
  { name: "Iraq", code: "IQ", currency: "IQD (ع.د) - Iraqi Dinar", currencyCode: "IQD", phoneCode: "+964", timezone: "Asia/Baghdad" },
  { name: "Ireland", code: "IE", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+353", timezone: "Europe/Dublin" },
  { name: "Israel", code: "IL", currency: "ILS (₪) - Israeli New Shekel", currencyCode: "ILS", phoneCode: "+972", timezone: "Asia/Jerusalem" },
  { name: "Italy", code: "IT", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+39", timezone: "Europe/Rome" },
  { name: "Jamaica", code: "JM", currency: "JMD (J$) - Jamaican Dollar", currencyCode: "JMD", phoneCode: "+1-876", timezone: "America/Jamaica" },
  { name: "Japan", code: "JP", currency: "JPY (¥) - Japanese Yen", currencyCode: "JPY", phoneCode: "+81", timezone: "Asia/Tokyo" },
  { name: "Jordan", code: "JO", currency: "JOD (د.ا) - Jordanian Dinar", currencyCode: "JOD", phoneCode: "+962", timezone: "Asia/Amman" },
  { name: "Kazakhstan", code: "KZ", currency: "KZT (₸) - Kazakhstani Tenge", currencyCode: "KZT", phoneCode: "+7", timezone: "Asia/Almaty" },
  { name: "Kenya", code: "KE", currency: "KES (KSh) - Kenyan Shilling", currencyCode: "KES", phoneCode: "+254", timezone: "Africa/Nairobi" },
  { name: "Kuwait", code: "KW", currency: "KWD (د.ك) - Kuwaiti Dinar", currencyCode: "KWD", phoneCode: "+965", timezone: "Asia/Kuwait" },
  { name: "Kyrgyzstan", code: "KG", currency: "KGS (с) - Kyrgyzstani Som", currencyCode: "KGS", phoneCode: "+996", timezone: "Asia/Bishkek" },
  { name: "Laos", code: "LA", currency: "LAK (₭) - Lao Kip", currencyCode: "LAK", phoneCode: "+856", timezone: "Asia/Vientiane" },
  { name: "Latvia", code: "LV", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+371", timezone: "Europe/Riga" },
  { name: "Lebanon", code: "LB", currency: "LBP (ل.ل) - Lebanese Pound", currencyCode: "LBP", phoneCode: "+961", timezone: "Asia/Beirut" },
  { name: "Lithuania", code: "LT", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+370", timezone: "Europe/Vilnius" },
  { name: "Luxembourg", code: "LU", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+352", timezone: "Europe/Luxembourg" },
  { name: "Macau", code: "MO", currency: "MOP (MOP$) - Macanese Pataca", currencyCode: "MOP", phoneCode: "+853", timezone: "Asia/Macau" },
  { name: "Madagascar", code: "MG", currency: "MGA (Ar) - Malagasy Ariary", currencyCode: "MGA", phoneCode: "+261", timezone: "Indian/Antananarivo" },
  { name: "Malaysia", code: "MY", currency: "MYR (RM) - Malaysian Ringgit", currencyCode: "MYR", phoneCode: "+60", timezone: "Asia/Kuala_Lumpur" },
  { name: "Maldives", code: "MV", currency: "MVR (Rf) - Maldivian Rufiyaa", currencyCode: "MVR", phoneCode: "+960", timezone: "Indian/Maldives" },
  { name: "Malta", code: "MT", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+356", timezone: "Europe/Malta" },
  { name: "Mauritius", code: "MU", currency: "MUR (₨) - Mauritian Rupee", currencyCode: "MUR", phoneCode: "+230", timezone: "Indian/Mauritius" },
  { name: "Mexico", code: "MX", currency: "MXN ($) - Mexican Peso", currencyCode: "MXN", phoneCode: "+52", timezone: "America/Mexico_City" },
  { name: "Moldova", code: "MD", currency: "MDL (L) - Moldovan Leu", currencyCode: "MDL", phoneCode: "+373", timezone: "Europe/Chisinau" },
  { name: "Monaco", code: "MC", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+377", timezone: "Europe/Monaco" },
  { name: "Mongolia", code: "MN", currency: "MNT (₮) - Mongolian Tögrög", currencyCode: "MNT", phoneCode: "+976", timezone: "Asia/Ulaanbaatar" },
  { name: "Montenegro", code: "ME", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+382", timezone: "Europe/Podgorica" },
  { name: "Morocco", code: "MA", currency: "MAD (د.م.) - Moroccan Dirham", currencyCode: "MAD", phoneCode: "+212", timezone: "Africa/Casablanca" },
  { name: "Mozambique", code: "MZ", currency: "MZN (MT) - Mozambican Metical", currencyCode: "MZN", phoneCode: "+258", timezone: "Africa/Maputo" },
  { name: "Myanmar", code: "MM", currency: "MMK (Ks) - Myanmar Kyat", currencyCode: "MMK", phoneCode: "+95", timezone: "Asia/Yangon" },
  { name: "Nepal", code: "NP", currency: "NPR (₨) - Nepalese Rupee", currencyCode: "NPR", phoneCode: "+977", timezone: "Asia/Kathmandu" },
  { name: "Netherlands", code: "NL", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+31", timezone: "Europe/Amsterdam" },
  { name: "New Zealand", code: "NZ", currency: "NZD ($) - New Zealand Dollar", currencyCode: "NZD", phoneCode: "+64", timezone: "Pacific/Auckland" },
  { name: "Nicaragua", code: "NI", currency: "NIO (C$) - Nicaraguan Córdoba", currencyCode: "NIO", phoneCode: "+505", timezone: "America/Managua" },
  { name: "Nigeria", code: "NG", currency: "NGN (₦) - Nigerian Naira", currencyCode: "NGN", phoneCode: "+234", timezone: "Africa/Lagos" },
  { name: "North Macedonia", code: "MK", currency: "MKD (ден) - Macedonian Denar", currencyCode: "MKD", phoneCode: "+389", timezone: "Europe/Skopje" },
  { name: "Norway", code: "NO", currency: "NOK (kr) - Norwegian Krone", currencyCode: "NOK", phoneCode: "+47", timezone: "Europe/Oslo" },
  { name: "Oman", code: "OM", currency: "OMR (ر.ع.) - Omani Rial", currencyCode: "OMR", phoneCode: "+968", timezone: "Asia/Muscat" },
  { name: "Pakistan", code: "PK", currency: "PKR (₨) - Pakistani Rupee", currencyCode: "PKR", phoneCode: "+92", timezone: "Asia/Karachi" },
  { name: "Panama", code: "PA", currency: "PAB (B/.) - Panamanian Balboa", currencyCode: "PAB", phoneCode: "+507", timezone: "America/Panama" },
  { name: "Papua New Guinea", code: "PG", currency: "PGK (K) - Papua New Guinean Kina", currencyCode: "PGK", phoneCode: "+675", timezone: "Pacific/Port_Moresby" },
  { name: "Paraguay", code: "PY", currency: "PYG (₲) - Paraguayan Guaraní", currencyCode: "PYG", phoneCode: "+595", timezone: "America/Asuncion" },
  { name: "Peru", code: "PE", currency: "PEN (S/.) - Peruvian Sol", currencyCode: "PEN", phoneCode: "+51", timezone: "America/Lima" },
  { name: "Philippines", code: "PH", currency: "PHP (₱) - Philippine Peso", currencyCode: "PHP", phoneCode: "+63", timezone: "Asia/Manila" },
  { name: "Poland", code: "PL", currency: "PLN (zł) - Polish Złoty", currencyCode: "PLN", phoneCode: "+48", timezone: "Europe/Warsaw" },
  { name: "Portugal", code: "PT", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+351", timezone: "Europe/Lisbon" },
  { name: "Qatar", code: "QA", currency: "QAR (ر.ق) - Qatari Riyal", currencyCode: "QAR", phoneCode: "+974", timezone: "Asia/Qatar" },
  { name: "Romania", code: "RO", currency: "RON (lei) - Romanian Leu", currencyCode: "RON", phoneCode: "+40", timezone: "Europe/Bucharest" },
  { name: "Russia", code: "RU", currency: "RUB (₽) - Russian Ruble", currencyCode: "RUB", phoneCode: "+7", timezone: "Europe/Moscow" },
  { name: "Rwanda", code: "RW", currency: "RWF (FRw) - Rwandan Franc", currencyCode: "RWF", phoneCode: "+250", timezone: "Africa/Kigali" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR (﷼) - Saudi Riyal", currencyCode: "SAR", phoneCode: "+966", timezone: "Asia/Riyadh" },
  { name: "Senegal", code: "SN", currency: "XOF (CFA) - West African CFA Franc", currencyCode: "XOF", phoneCode: "+221", timezone: "Africa/Dakar" },
  { name: "Serbia", code: "RS", currency: "RSD (дин.) - Serbian Dinar", currencyCode: "RSD", phoneCode: "+381", timezone: "Europe/Belgrade" },
  { name: "Singapore", code: "SG", currency: "SGD ($) - Singapore Dollar", currencyCode: "SGD", phoneCode: "+65", timezone: "Asia/Singapore" },
  { name: "Slovakia", code: "SK", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+421", timezone: "Europe/Bratislava" },
  { name: "Slovenia", code: "SI", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+386", timezone: "Europe/Ljubljana" },
  { name: "South Africa", code: "ZA", currency: "ZAR (R) - South African Rand", currencyCode: "ZAR", phoneCode: "+27", timezone: "Africa/Johannesburg" },
  { name: "South Korea", code: "KR", currency: "KRW (₩) - South Korean Won", currencyCode: "KRW", phoneCode: "+82", timezone: "Asia/Seoul" },
  { name: "Spain", code: "ES", currency: "EUR (€) - Euro", currencyCode: "EUR", phoneCode: "+34", timezone: "Europe/Madrid" },
  { name: "Sri Lanka", code: "LK", currency: "LKR (Rs) - Sri Lankan Rupee", currencyCode: "LKR", phoneCode: "+94", timezone: "Asia/Colombo" },
  { name: "Sweden", code: "SE", currency: "SEK (kr) - Swedish Krona", currencyCode: "SEK", phoneCode: "+46", timezone: "Europe/Stockholm" },
  { name: "Switzerland", code: "CH", currency: "CHF (CHF) - Swiss Franc", currencyCode: "CHF", phoneCode: "+41", timezone: "Europe/Zurich" },
  { name: "Taiwan", code: "TW", currency: "TWD (NT$) - New Taiwan Dollar", currencyCode: "TWD", phoneCode: "+886", timezone: "Asia/Taipei" },
  { name: "Tanzania", code: "TZ", currency: "TZS (TSh) - Tanzanian Shilling", currencyCode: "TZS", phoneCode: "+255", timezone: "Africa/Dar_es_Salaam" },
  { name: "Thailand", code: "TH", currency: "THB (฿) - Thai Baht", currencyCode: "THB", phoneCode: "+66", timezone: "Asia/Bangkok" },
  { name: "Trinidad and Tobago", code: "TT", currency: "TTD (TT$) - Trinidad and Tobago Dollar", currencyCode: "TTD", phoneCode: "+1-868", timezone: "America/Port_of_Spain" },
  { name: "Tunisia", code: "TN", currency: "TND (د.ت) - Tunisian Dinar", currencyCode: "TND", phoneCode: "+216", timezone: "Africa/Tunis" },
  { name: "Turkey", code: "TR", currency: "TRY (₺) - Turkish Lira", currencyCode: "TRY", phoneCode: "+90", timezone: "Europe/Istanbul" },
  { name: "Uganda", code: "UG", currency: "UGX (USh) - Ugandan Shilling", currencyCode: "UGX", phoneCode: "+256", timezone: "Africa/Kampala" },
  { name: "Ukraine", code: "UA", currency: "UAH (₴) - Ukrainian Hryvnia", currencyCode: "UAH", phoneCode: "+380", timezone: "Europe/Kyiv" },
  { name: "United Arab Emirates", code: "AE", currency: "AED (د.إ) - UAE Dirham", currencyCode: "AED", phoneCode: "+971", timezone: "Asia/Dubai" },
  { name: "United Kingdom", code: "GB", currency: "GBP (£) - British Pound", currencyCode: "GBP", phoneCode: "+44", timezone: "Europe/London" },
  { name: "United States", code: "US", currency: "USD ($) - US Dollar", currencyCode: "USD", phoneCode: "+1", timezone: "America/New_York" },
  { name: "Uruguay", code: "UY", currency: "UYU ($U) - Uruguayan Peso", currencyCode: "UYU", phoneCode: "+598", timezone: "America/Montevideo" },
  { name: "Uzbekistan", code: "UZ", currency: "UZS (soʻm) - Uzbekistani Soʻm", currencyCode: "UZS", phoneCode: "+998", timezone: "Asia/Tashkent" },
  { name: "Venezuela", code: "VE", currency: "VES (Bs.S) - Venezuelan Bolívar", currencyCode: "VES", phoneCode: "+58", timezone: "America/Caracas" },
  { name: "Vietnam", code: "VN", currency: "VND (₫) - Vietnamese Đồng", currencyCode: "VND", phoneCode: "+84", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Zambia", code: "ZM", currency: "ZMW (ZK) - Zambian Kwacha", currencyCode: "ZMW", phoneCode: "+260", timezone: "Africa/Lusaka" },
  { name: "Zimbabwe", code: "ZW", currency: "ZWG (ZiG) - Zimbabwean Gold", currencyCode: "ZWG", phoneCode: "+263", timezone: "Africa/Harare" }
];

export const BUSINESS_CATEGORIES = [
  { value: "retail", label: "General Retail" },
  { value: "fashion", label: "Apparel, Fashion & Clothing" },
  { value: "beauty", label: "Beauty, Cosmetics & Personal Care" },
  { value: "electronics", label: "Electronics, Computers & Gadgets" },
  { value: "food", label: "Food, Beverages & Groceries" },
  { value: "health", label: "Health, Wellness & Pharmacy" },
  { value: "home", label: "Home Decor, Furniture & Kitchen" },
  { value: "jewelry", label: "Jewelry, Watches & Accessories" },
  { value: "sports", label: "Sports, Fitness & Outdoor" },
  { value: "kids", label: "Toys, Kids & Baby Products" },
  { value: "automotive", label: "Automotive & Industrial" },
  { value: "books", label: "Books, Stationery & Media" },
  { value: "art", label: "Art, Crafts & Collectibles" },
  { value: "services", label: "Services & Appointments" },
  { value: "digital", label: "Digital Products & Subscriptions" },
  { value: "other", label: "Other / Specialized Business" }
];

export const CURRENCIES = [
  { value: "CAD", label: "CAD", subLabel: "Canada Dollar", symbol: "$" },
  { value: "INR", label: "INR", subLabel: "India Rupee", symbol: "₹" },
  { value: "USD", label: "USD", subLabel: "United States Dollar", symbol: "$" },
  { value: "EUR", label: "EUR", subLabel: "Eurozone Euro", symbol: "€" },
  { value: "GBP", label: "GBP", subLabel: "United Kingdom Pound", symbol: "£" },
  { value: "AUD", label: "AUD", subLabel: "Australia Dollar", symbol: "$" },
  { value: "AED", label: "AED", subLabel: "UAE Dirham", symbol: "د.إ" },
  { value: "SAR", label: "SAR", subLabel: "Saudi Arabia Riyal", symbol: "﷼" },
  { value: "SGD", label: "SGD", subLabel: "Singapore Dollar", symbol: "$" },
  { value: "JPY", label: "JPY", subLabel: "Japan Yen", symbol: "¥" },
  { value: "CNY", label: "CNY", subLabel: "China Yuan", symbol: "¥" },
  { value: "KRW", label: "KRW", subLabel: "South Korea Won", symbol: "₩" },
  { value: "BRL", label: "BRL", subLabel: "Brazil Real", symbol: "R$" },
  { value: "MXN", label: "MXN", subLabel: "Mexico Peso", symbol: "$" },
  { value: "ZAR", label: "ZAR", subLabel: "South Africa Rand", symbol: "R" },
  { value: "NZD", label: "NZD", subLabel: "New Zealand Dollar", symbol: "$" },
  { value: "CHF", label: "CHF", subLabel: "Switzerland Franc", symbol: "CHF" },
  { value: "HKD", label: "HKD", subLabel: "Hong Kong Dollar", symbol: "$" },
  { value: "MYR", label: "MYR", subLabel: "Malaysia Ringgit", symbol: "RM" },
  { value: "IDR", label: "IDR", subLabel: "Indonesia Rupiah", symbol: "Rp" },
  { value: "SEK", label: "SEK", subLabel: "Sweden Krona", symbol: "kr" },
  { value: "NOK", label: "NOK", subLabel: "Norway Krone", symbol: "kr" },
  { value: "DKK", label: "DKK", subLabel: "Denmark Krone", symbol: "kr" },
  { value: "PLN", label: "PLN", subLabel: "Poland Złoty", symbol: "zł" },
  { value: "TRY", label: "TRY", subLabel: "Turkey Lira", symbol: "₺" },
  { value: "THB", label: "THB", subLabel: "Thailand Baht", symbol: "฿" },
  { value: "PHP", label: "PHP", subLabel: "Philippines Peso", symbol: "₱" },
  { value: "VND", label: "VND", subLabel: "Vietnam Đồng", symbol: "₫" },
  { value: "EGP", label: "EGP", subLabel: "Egypt Pound", symbol: "E£" },
  { value: "NGN", label: "NGN", subLabel: "Nigeria Naira", symbol: "₦" },
  { value: "KES", label: "KES", subLabel: "Kenya Shilling", symbol: "KSh" },
  { value: "ARS", label: "ARS", subLabel: "Argentina Peso", symbol: "$" },
  { value: "CLP", label: "CLP", subLabel: "Chile Peso", symbol: "$" },
  { value: "COP", label: "COP", subLabel: "Colombia Peso", symbol: "$" },
  { value: "PEN", label: "PEN", subLabel: "Peru Sol", symbol: "S/." },
  { value: "ILS", label: "ILS", subLabel: "Israel New Shekel", symbol: "₪" },
  { value: "RUB", label: "RUB", subLabel: "Russia Ruble", symbol: "₽" }
];

export const TIMEZONES = [
  { value: "Asia/Kolkata", label: "Asia/Kolkata (IST - UTC+5:30)" },
  { value: "America/New_York", label: "America/New_York (EST/EDT - UTC-5/4)" },
  { value: "America/Chicago", label: "America/Chicago (CST/CDT - UTC-6/5)" },
  { value: "America/Denver", label: "America/Denver (MST/MDT - UTC-7/6)" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles (PST/PDT - UTC-8/7)" },
  { value: "Europe/London", label: "Europe/London (GMT/BST - UTC+0/1)" },
  { value: "Europe/Berlin", label: "Europe/Berlin (CET/CEST - UTC+1/2)" },
  { value: "Europe/Paris", label: "Europe/Paris (CET/CEST - UTC+1/2)" },
  { value: "Europe/Rome", label: "Europe/Rome (CET/CEST - UTC+1/2)" },
  { value: "Europe/Madrid", label: "Europe/Madrid (CET/CEST - UTC+1/2)" },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam (CET/CEST - UTC+1/2)" },
  { value: "Asia/Dubai", label: "Asia/Dubai (GST - UTC+4)" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh (AST - UTC+3)" },
  { value: "Asia/Singapore", label: "Asia/Singapore (SGT - UTC+8)" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (JST - UTC+9)" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (CST - UTC+8)" },
  { value: "Asia/Seoul", label: "Asia/Seoul (KST - UTC+9)" },
  { value: "Australia/Sydney", label: "Australia/Sydney (AEST/AEDT - UTC+10/11)" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne (AEST/AEDT - UTC+10/11)" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland (NZST/NZDT - UTC+12/13)" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo (BRT - UTC-3)" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg (SAST - UTC+2)" },
  { value: "UTC", label: "UTC (Universal Coordinated Time)" }
];
